stages:
  - analysis
  - build
  - test
  - coverage
  - deploy

before_script:
  - hostname
  - whoami
# - pwd
  - git submodule sync --recursive
  - git submodule update --init --recursive

analysis-cppcheck:
  stage: analysis
  artifacts:
    name: analysis-cppcheck-logs
    when: always
    paths:
      - cppcheck/
  tags:
    - cppcheck
  script:
    - ./ci/analysis-cppcheck.sh

# ---------------------------------------------------------------------------------------------------------------------
# LINUX X86 -----------------------------------------------------------------------------------------------------------

# BUILDS --------------------------------------------------------------------------------------------------------------

build-linux-x86-gcc:
  stage: build
  tags:
    - linux
    - x86
    - gcc
    - cmake
  artifacts:
    paths:
      - ./tests/build_linux_x86_gcc_nointr/bin/
      - ./tests/build_linux_x86_gcc_sse2/bin/
      - ./tests/build_linux_x86_gcc_sse3/bin/
      - ./tests/build_linux_x86_gcc_ssse3/bin/
      - ./tests/build_linux_x86_gcc_sse4_1/bin/
      - ./tests/build_linux_x86_gcc_sse4_2/bin/
      - ./tests/build_linux_x86_gcc_avx/bin/
      - ./tests/build_linux_x86_gcc_avx2/bin/
      - ./tests/build_linux_x86_gcc_avx2_fma/bin/
      - ./tests/build_linux_x86_gcc_avx512f/bin/
  script:
    - ./ci/build-linux-x86-gcc.sh

build-linux-x86-clang:
  stage: build
  tags:
    - linux
    - x86
    - clang
    - cmake
  artifacts:
    paths:
      - ./tests/build_linux_x86_clang_nointr/bin/
      - ./tests/build_linux_x86_clang_sse2/bin/
      - ./tests/build_linux_x86_clang_sse3/bin/
      - ./tests/build_linux_x86_clang_ssse3/bin/
      - ./tests/build_linux_x86_clang_sse4_1/bin/
      - ./tests/build_linux_x86_clang_sse4_2/bin/
      - ./tests/build_linux_x86_clang_avx/bin/
      - ./tests/build_linux_x86_clang_avx2/bin/
      - ./tests/build_linux_x86_clang_avx2_fma/bin/
  script:
    - ./ci/build-linux-x86-clang.sh

build-linux-x86-icpc:
  stage: build
  tags:
    - linux
    - x86
    - icpc
    - cmake
  artifacts:
    paths:
      - ./tests/build_linux_x86_icpc_nointr/bin/
      - ./tests/build_linux_x86_icpc_sse2/bin/
      - ./tests/build_linux_x86_icpc_sse3/bin/
      - ./tests/build_linux_x86_icpc_ssse3/bin/
      - ./tests/build_linux_x86_icpc_sse4_1/bin/
      - ./tests/build_linux_x86_icpc_sse4_2/bin/
      - ./tests/build_linux_x86_icpc_avx/bin/
      - ./tests/build_linux_x86_icpc_avx2_fma/bin/
      - ./tests/build_linux_x86_icpc_avx512f/bin/
  script:
    - ./ci/build-linux-x86-icpc.sh

# TESTS ---------------------------------------------------------------------------------------------------------------

test-linux-x86-unit-nointr:
  stage: test
  dependencies:
    - build-linux-x86-gcc
    - build-linux-x86-clang
    - build-linux-x86-icpc
  tags:
    - linux
    - x86
  script:
    - ./ci/test-linux-macos-unit.sh build_linux_x86_gcc_nointr build_linux_x86_clang_nointr build_linux_x86_icpc_nointr

test-linux-x86-unit-sse2:
  stage: test
  dependencies:
    - build-linux-x86-gcc
    - build-linux-x86-clang
    - build-linux-x86-icpc
  tags:
    - linux
    - x86
    - sse2
  script:
    - ./ci/test-linux-macos-unit.sh build_linux_x86_gcc_sse2 build_linux_x86_clang_sse2 build_linux_x86_icpc_sse2

test-linux-x86-unit-sse3:
  stage: test
  dependencies:
    - build-linux-x86-gcc
    - build-linux-x86-clang
    - build-linux-x86-icpc
  tags:
    - linux
    - x86
    - sse3
  script:
    - ./ci/test-linux-macos-unit.sh build_linux_x86_gcc_sse3 build_linux_x86_clang_sse3 build_linux_x86_icpc_sse3

test-linux-x86-unit-ssse3:
  stage: test
  dependencies:
    - build-linux-x86-gcc
    - build-linux-x86-clang
    - build-linux-x86-icpc
  tags:
    - linux
    - x86
    - ssse3
  script:
    - ./ci/test-linux-macos-unit.sh build_linux_x86_gcc_ssse3 build_linux_x86_clang_ssse3 build_linux_x86_icpc_ssse3

test-linux-x86-unit-sse4_1:
  stage: test
  dependencies:
    - build-linux-x86-gcc
    - build-linux-x86-clang
    - build-linux-x86-icpc
  tags:
    - linux
    - x86
    - sse4.1
  script:
    - ./ci/test-linux-macos-unit.sh build_linux_x86_gcc_sse4_1 build_linux_x86_clang_sse4_1 build_linux_x86_icpc_sse4_1

test-linux-x86-unit-sse4_2:
  stage: test
  dependencies:
    - build-linux-x86-gcc
    - build-linux-x86-clang
    - build-linux-x86-icpc
  tags:
    - linux
    - x86
    - sse4.2
  script:
    - ./ci/test-linux-macos-unit.sh build_linux_x86_gcc_sse4_2 build_linux_x86_clang_sse4_2 build_linux_x86_icpc_sse4_2

test-linux-x86-unit-avx:
  stage: test
  dependencies:
    - build-linux-x86-gcc
    - build-linux-x86-clang
    - build-linux-x86-icpc
  tags:
    - linux
    - x86
    - avx
  script:
    - ./ci/test-linux-macos-unit.sh build_linux_x86_gcc_avx build_linux_x86_clang_avx build_linux_x86_icpc_avx

# test-linux-x86-unit-avx2:
#   stage: test
#   dependencies:
#     - build-linux-x86-gcc
#     - build-linux-x86-clang
#     - build-linux-x86-icpc
#   tags:
#     - linux
#     - x86
#     - avx2
#   script:
#     - ./ci/test-linux-macos-unit.sh build_linux_x86_gcc_avx2 build_linux_x86_clang_avx2

# test-linux-x86-unit-avx2-fma:
#   stage: test
#   dependencies:
#     - build-linux-x86-gcc
#     - build-linux-x86-clang
#     - build-linux-x86-icpc
#   tags:
#     - linux
#     - x86
#     - avx2
#   script:
#     - ./ci/test-linux-macos-unit.sh build_linux_x86_gcc_avx2_fma build_linux_x86_clang_avx2_fma build_linux_x86_icpc_avx2_fma


# test-linux-x86-unit-avx512f:
#   stage: test
#   dependencies:
#     - build-linux-x86-gcc
#     - build-linux-x86-clang
#     - build-linux-x86-icpc
#   tags:
#     - linux
#     - x86
#     - avx512f
#   script:
#     - ./ci/test-linux-macos-unit.sh build_linux_x86_gcc_avx512f build_linux_x86_clang_avx512f build_linux_x86_icpc_avx512f

# ---------------------------------------------------------------------------------------------------------------------
# MACOSX X86 ----------------------------------------------------------------------------------------------------------

# BUILDS --------------------------------------------------------------------------------------------------------------

build-macos-x86-clang:
  stage: build
  tags:
    - macos
    - x86
    - apple-clang
    - cmake
  artifacts:
    paths:
      - ./tests/build_macos_x86_clang_nointr/bin/
      - ./tests/build_macos_x86_clang_sse2/bin/
      - ./tests/build_macos_x86_clang_sse3/bin/
      - ./tests/build_macos_x86_clang_ssse3/bin/
      - ./tests/build_macos_x86_clang_sse4_1/bin/
      - ./tests/build_macos_x86_clang_sse4_2/bin/
      - ./tests/build_macos_x86_clang_avx/bin/
      - ./tests/build_macos_x86_clang_avx2/bin/
      - ./tests/build_macos_x86_clang_avx2_fma/bin/
  script:
    - ./ci/build-macos-x86-clang.sh

# TESTS ---------------------------------------------------------------------------------------------------------------

test-macos-x86-unit-nointr:
  stage: test
  dependencies:
    - build-macos-x86-clang
  tags:
     - macos
     - x86
  script:
    - ./ci/test-linux-macos-unit.sh build_macos_x86_clang_nointr

test-macos-x86-unit-sse2:
  stage: test
  dependencies:
    - build-macos-x86-clang
  tags:
    - macos
    - x86
    - sse2
  script:
    - ./ci/test-linux-macos-unit.sh build_macos_x86_clang_sse2

test-macos-x86-unit-sse3:
  stage: test
  dependencies:
    - build-macos-x86-clang
  tags:
    - macos
    - x86
    - sse3
  script:
    - ./ci/test-linux-macos-unit.sh build_macos_x86_clang_sse3

test-macos-x86-unit-ssse3:
  stage: test
  dependencies:
    - build-macos-x86-clang
  tags:
    - macos
    - x86
    - ssse3
  script:
    - ./ci/test-linux-macos-unit.sh build_macos_x86_clang_ssse3

test-macos-x86-unit-sse4_1:
  stage: test
  dependencies:
    - build-macos-x86-clang
  tags:
    - macos
    - x86
    - sse4.1
  script:
    - ./ci/test-linux-macos-unit.sh build_macos_x86_clang_sse4_1

test-macos-x86-unit-sse4_2:
  stage: test
  dependencies:
    - build-macos-x86-clang
  tags:
    - macos
    - x86
    - sse4.2
  script:
    - ./ci/test-linux-macos-unit.sh build_macos_x86_clang_sse4_2

test-macos-x86-unit-avx:
  stage: test
  dependencies:
    - build-macos-x86-clang
  tags:
    - macos
    - x86
    - avx
  script:
    - ./ci/test-linux-macos-unit.sh build_macos_x86_clang_avx

# test-macos-x86-unit-avx2:
#   stage: test
#   dependencies:
#    - build-macos-x86-clang
#   tags:
#     - macos
#     - x86
#     - avx2
#   script:
#     - ./ci/test-linux-macos-unit.sh build_macos_x86_clang_avx2

# test-macos-x86-unit-avx2-fma:
#   stage: test
#   dependencies:
#     - build-macos-x86-clang
#   tags:
#     - macos
#     - x86
#     - avx2
#   script:
#     - ./ci/test-linux-macos-unit.sh build_macos_x86_clang_avx2_fma

# test-macos-x86-unit-avx512f:
#   stage: test
#   dependencies:
#     - build-macos-x86-clang
#   tags:
#     - macos
#     - x86
#     - avx512f
#   script:
#     - ./ci/test-linux-macos-unit.sh build_macos_x86_clang_avx512f

# ---------------------------------------------------------------------------------------------------------------------
# LINUX ARM -----------------------------------------------------------------------------------------------------------

# BUILDS --------------------------------------------------------------------------------------------------------------

build-linux-armv7-gcc:
  stage: build
  tags:
    - linux
    - armv7
    - gcc
    - cmake
  artifacts:
    paths:
      - ./tests/build_linux_armv7_gcc_nointr/bin/
      - ./tests/build_linux_armv7_gcc_neon32/bin/
      - ./tests/build_linux_armv7_gcc_neon32_fma/bin/
  script:
    - ./ci/build-linux-armv7-gcc.sh

build-linux-armv7-clang:
  stage: build
  tags:
    - linux
    - armv7
    - clang
    - cmake
  artifacts:
    paths:
      - ./tests/build_linux_armv7_clang_nointr/bin/
      - ./tests/build_linux_armv7_clang_neon32/bin/
      - ./tests/build_linux_armv7_clang_neon32_fma/bin/
  script:
    - ./ci/build-linux-armv7-clang.sh

build-linux-armv8-gcc:
  stage: build
  tags:
    - linux
    - armv8
    - gcc
    - cmake
  artifacts:
    paths:
      - ./tests/build_linux_armv8_gcc_nointr/bin/
      - ./tests/build_linux_armv8_gcc_neon64/bin/
  script:
    - ./ci/build-linux-armv8-gcc.sh

build-linux-armv8-clang:
  stage: build
  tags:
    - linux
    - armv8
    - clang
    - cmake
  artifacts:
    paths:
      - ./tests/build_linux_armv8_clang_nointr/bin/
      - ./tests/build_linux_armv8_clang_neon64/bin/
  script:
    - ./ci/build-linux-armv8-clang.sh

# TESTS ---------------------------------------------------------------------------------------------------------------

test-linux-armv7-unit-nointr:
  stage: test
  dependencies:
    - build-linux-armv7-gcc
    - build-linux-armv7-clang
  tags:
    - linux
    - armv7
  script:
    - ./ci/test-linux-macos-unit.sh build_linux_armv7_gcc_nointr build_linux_armv7_clang_nointr

test-linux-armv7-unit-neon32:
  stage: test
  dependencies:
    - build-linux-armv7-gcc
    - build-linux-armv7-clang
  tags:
    - linux
    - armv7
    - neon32
  script:
    - ./ci/test-linux-macos-unit.sh build_linux_armv7_gcc_neon32 build_linux_armv7_clang_neon32

test-linux-armv7-unit-neon32-fma:
  stage: test
  dependencies:
    - build-linux-armv7-gcc
    - build-linux-armv7-clang
  tags:
    - linux
    - armv7
    - neon32-fma
  script:
    - ./ci/test-linux-macos-unit.sh build_linux_armv7_gcc_neon32_fma build_linux_armv7_clang_neon32_fma

test-linux-armv8-unit-nointr:
  stage: test
  dependencies:
    - build-linux-armv8-gcc
    - build-linux-armv8-clang
  tags:
    - linux
    - armv8
  script:
    - ./ci/test-linux-macos-unit.sh build_linux_armv8_gcc_nointr build_linux_armv8_clang_nointr

test-linux-armv8-unit-neon64:
  stage: test
  dependencies:
    - build-linux-armv8-gcc
    - build-linux-armv8-clang
  tags:
    - linux
    - armv8
    - neon64
  script:
    - ./ci/test-linux-macos-unit.sh build_linux_armv8_gcc_neon64 build_linux_armv8_clang_neon64

# ---------------------------------------------------------------------------------------------------------------------
# WINDOWS X86 ---------------------------------------------------------------------------------------------------------

# BUILDS --------------------------------------------------------------------------------------------------------------

build-windows-x86-gcc:
  stage: build
  tags:
    - windows
    - x86
    - gcc
    - cmake
  artifacts:
    paths:
      - ./tests/build_windows_x86_gcc_nointr/bin/
      - ./tests/build_windows_x86_gcc_sse2/bin/
      - ./tests/build_windows_x86_gcc_sse3/bin/
      - ./tests/build_windows_x86_gcc_ssse3/bin/
      - ./tests/build_windows_x86_gcc_sse4_1/bin/
      - ./tests/build_windows_x86_gcc_sse4_2/bin/
      - ./tests/build_windows_x86_gcc_avx/bin/
      - ./tests/build_windows_x86_gcc_avx2/bin/
      - ./tests/build_windows_x86_gcc_avx2_fma/bin/
      # - ./tests/build_windows_x86_gcc_avx512f/bin/
  script:
    - ./ci/build-windows-x86-gcc.bat

build-windows-x86-msvc:
  stage: build
  tags:
    - windows
    - x86
    - msvc
    - cmake
  artifacts:
    paths:
      - ./tests/build_windows_x86_msvc_nointr/bin/
      - ./tests/build_windows_x86_msvc_sse2/bin/
      - ./tests/build_windows_x86_msvc_sse3/bin/
      - ./tests/build_windows_x86_msvc_ssse3/bin/
      - ./tests/build_windows_x86_msvc_sse4_1/bin/
      - ./tests/build_windows_x86_msvc_sse4_2/bin/
      - ./tests/build_windows_x86_msvc_avx/bin/
      - ./tests/build_windows_x86_msvc_avx2_fma/bin/
      # - ./tests/build_windows_x86_msvc_avx512f/bin/
  script:
    - ./ci/build-windows-x86-msvc.bat

# TESTS ---------------------------------------------------------------------------------------------------------------

test-windows-x86-unit-nointr:
  stage: test
  dependencies:
    - build-windows-x86-gcc
    - build-windows-x86-msvc
  tags:
     - windows
     - x86
  script:
    - ./ci/test-windows-unit.bat build_windows_x86_gcc_nointr build_windows_x86_msvc_nointr

test-windows-x86-unit-sse2:
  stage: test
  dependencies:
    - build-windows-x86-gcc
    - build-windows-x86-msvc
  tags:
    - windows
    - x86
    - sse2
  script:
    - ./ci/test-windows-unit.bat build_windows_x86_gcc_sse2 build_windows_x86_msvc_sse2

test-windows-x86-unit-sse3:
  stage: test
  dependencies:
    - build-windows-x86-gcc
    - build-windows-x86-msvc
  tags:
    - windows
    - x86
    - sse3
  script:
    - ./ci/test-windows-unit.bat build_windows_x86_gcc_sse3 build_windows_x86_msvc_sse3

test-windows-x86-unit-ssse3:
  stage: test
  dependencies:
    - build-windows-x86-gcc
    - build-windows-x86-msvc
  tags:
    - windows
    - x86
    - ssse3
  script:
    - ./ci/test-windows-unit.bat build_windows_x86_gcc_ssse3 build_windows_x86_msvc_ssse3

test-windows-x86-unit-sse4_1:
  stage: test
  dependencies:
    - build-windows-x86-gcc
    - build-windows-x86-msvc
  tags:
    - windows
    - windows
    - x86
    - sse4.1
  script:
    - ./ci/test-windows-unit.bat build_windows_x86_gcc_sse4_1 build_windows_x86_msvc_sse4_1

test-windows-x86-unit-sse4_2:
  stage: test
  dependencies:
    - build-windows-x86-gcc
    - build-windows-x86-msvc
  tags:
    - windows
    - x86
    - sse4.2
  script:
    - ./ci/test-windows-unit.bat build_windows_x86_gcc_sse4_2 build_windows_x86_msvc_sse4_2

test-windows-x86-unit-avx:
  stage: test
  dependencies:
    - build-windows-x86-gcc
    - build-windows-x86-msvc
  tags:
    - windows
    - x86
    - avx
  script:
    - ./ci/test-windows-unit.bat build_windows_x86_gcc_avx build_windows_x86_msvc_avx

# test-windows-x86-unit-avx2:
#   stage: test
#   dependencies:
#     - build-windows-x86-gcc
#     - build-windows-x86-msvc
#   tags:
#     - windows
#     - x86
#     - avx2
#   script:
#     - ./ci/test-windows-unit.bat build_windows_x86_gcc_avx2 build_windows_x86_msvc_avx2

# test-windows-x86-unit-avx2-fma:
#   stage: test
#   dependencies:
#     - build-windows-x86-gcc
#     - build-windows-x86-msvc
#   tags:
#     - windows
#     - x86
#     - avx2
#   script:
#     - ./ci/test-windows-unit.bat build_windows_x86_gcc_avx2_fma build_windows_x86_msvc_avx2_fma


# test-windows-x86-unit-avx512f:
#   stage: test
#   dependencies:
#     - build-windows-x86-gcc
#     - build-windows-x86-msvc
#   tags:
#     - windows
#     - x86
#     - avx512f
#   script:
#     - ./ci/test-windows-unit.bat build_windows_x86_gcc_avx512f build_windows_x86_msvc_avx512f

# COVERAGE ---------------------------------------------------------------------------------------------------------------

build-coverage-linux-x86-gcc:
  stage: build
  tags:
    - lcov
    - linux
    - x86
    - gcc
    - cmake
  artifacts:
    name: code-coverage-files
    when: always
    paths:
      - ./tests/code_coverage_files/*
  script:
    - ./ci/build-coverage-linux-x86-gcc.sh

build-coverage-linux-armv7-gcc:
  stage: build
  tags:
    - lcov
    - linux
    - armv7
    - gcc
    - cmake
  artifacts:
    name: code-coverage-files
    paths:
      - ./tests/code_coverage_files/*
  script:
    - ./ci/build-coverage-linux-armv7-gcc.sh

build-coverage-linux-armv8-gcc:
  stage: build
  tags:
    - lcov
    - linux
    - armv8
    - gcc
    - cmake
  artifacts:
    name: code-coverage-files
    paths:
      - ./tests/code_coverage_files/*
  script:
    - ./ci/build-coverage-linux-armv8-gcc.sh

coverage-linux:
  stage: coverage
  dependencies:
    - build-coverage-linux-x86-gcc
    - build-coverage-linux-armv7-gcc
    - build-coverage-linux-armv8-gcc
  tags:
    - lcov
    - linux
  coverage: '/.*lines\.*: (\d+.\d+\%)/'
  artifacts:
     name: code-coverage-report
     paths:
      - ./tests/code_coverage_report/
  script:
    - ./ci/coverage-linux.sh

pages:
  stage: deploy
  tags:
    - linux
  dependencies:
    - coverage-linux
  script:
    - mv ./tests/code_coverage_report/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master